[list-last-projects]
command = "ls -lrt ${HOME}/projects"
description = """
    List my last projects.
    This contains a multiline description just to check what all of
    this looks like when rendered in the terminal.

        Here we add another indentation.
        This should definately be indented.

    This not anymore.
        But this again.
    Not anymore lol.
        ... But again?
"""

[actvenv]
name = "Activate Python .venv"
command = "source ./.venv/bin/activate"
description = "Activate the .venv python environment."
tags = [
    "python",
    "venv"
]
